// Shared layout of the two PDF CVs (resume.typ: 1 page, full.typ: 2 pages).
// Content comes from dist/cv/data.json, generated by the website build from
// src/data/*.yaml: edit the YAML files, not this template.

#let accent = rgb("#a3192e")
#let soft = rgb("#55565c")

// Tiny Markdown subset used in the YAML files: **bold**, *italic*.
#let md(s) = {
  let t = s
  for c in ("\\", "#", "$", "@", "<", ">", "_", "~", "`", "[", "]", "=", "-", "+", "/") {
    t = t.replace(c, "\\" + c)
  }
  t = t.replace(regex("\*\*(.+?)\*\*"), m => "BOLD{" + m.captures.at(0) + "}BOLD")
  t = t.replace(regex("\*(.+?)\*"), m => "\_" + m.captures.at(0) + "\_")
  t = t.replace("\\_", "_").replace("BOLD{", "*").replace("}BOLD", "*")
  eval(t, mode: "markup")
}

#let setup(body) = {
  set document(author: "Emilien Seiler")
  set page(paper: "a4", margin: (x: 1.55cm, top: 1.35cm, bottom: 1.2cm))
  set text(font: "Source Sans 3", size: 10pt, fill: rgb("#1b1b1f"), lang: "en")
  set par(justify: false, leading: 0.5em, spacing: 0.6em)
  set list(indent: 0.2em, body-indent: 0.5em, spacing: 0.38em, marker: text(fill: accent, "•"))
  show link: set text(fill: rgb("#1b1b1f"))
  body
}

#let header(data, phone: none) = {
  let p = data.profile
  let l = p.links
  let site = data.site.replace("https://", "")
  let items = (
    link("mailto:" + l.email, l.email),
    link(data.site, site),
    ..if l.at("github", default: "") != "" { (link(l.github, "github.com/" + l.github.split("/").last()),) },
    ..if l.at("scholar", default: "") != "" { (link(l.scholar, "Google Scholar"),) },
    ..if l.at("linkedin", default: "") != "" { (link(l.linkedin, "LinkedIn"),) },
    ..if phone != none and phone != "" { (phone,) },
  )
  align(center)[
    #text(font: "Source Serif 4", size: 21pt, weight: 600, p.name)
    #v(-0.55em)
    #text(size: 10.5pt, fill: soft)[#p.role · #p.affiliation]
    #v(-0.35em)
    #text(size: 9.5pt)[#items.join(h(0.45em) + text(fill: accent, "·") + h(0.45em))]
  ]
  v(0.1em)
}

#let section(title) = {
  v(0.55em)
  block(below: 0.45em, sticky: true)[  // never alone at the bottom of a page
    #text(size: 10.5pt, weight: 700, fill: accent, tracking: 0.06em, upper(title))
    #v(-0.62em)
    #line(length: 100%, stroke: 0.5pt + accent.lighten(55%))
  ]
}

// One CV entry. `short: true` uses the one-line `short` text when present.
#let entry(e, short: false) = {
  let org = e.at("org", default: none)
  // City only ("Lausanne, Switzerland" -> "Lausanne"); the 1-page resume leaves it out.
  let place = if short { none } else { e.at("place", default: none) }
  if place != none { place = place.split(",").first() }
  block(below: 0.55em, breakable: false)[
    #grid(
      columns: (1fr, auto),
      column-gutter: 1em,
      [*#e.title*#if org != none [, #org]#if place != none [#text(fill: soft)[ · #place]]],
      text(fill: soft, size: 9.5pt, str(e.period)),
    )
    #let s = e.at("short", default: none)
    #if short and s != none {
      if s != "" { v(-0.3em); text(size: 9.5pt, fill: soft, md(s)) }
    } else if e.at("details", default: ()).len() > 0 {
      v(-0.3em)
      set text(size: 9.5pt)
      list(..e.details.map(md))
    }
  ]
}

#let entries(list, short: false) = for e in list { entry(e, short: short) }

#let publication(p, i) = {
  let authors = p.authors.map(a => {
    let n = if a.equal { a.name + "*" } else { a.name }
    if a.me { text(weight: 700, n) } else { n }
  })
  block(below: 0.55em, breakable: false, grid(
    columns: (1.6em, 1fr),
    text(fill: soft, size: 9.5pt, "[" + str(i) + "]"),
    [
      #link(p.url, text(weight: 600, p.title)) \
      #text(size: 9.5pt)[#authors.join(", ")] \
      #text(size: 9.5pt, style: "italic", fill: accent, p.venue)
    ],
  ))
}

#let skills(list) = {
  set text(size: 9.5pt)
  block(breakable: false, grid(
    columns: (auto, 1fr),
    column-gutter: 1em,
    row-gutter: 0.5em,
    ..list.map(s => (text(weight: 700, s.group), s.items.join(", "))).flatten(),
  ))
}

#let research(data) = data.cv.experience.filter(e => e.at("kind", default: "research") != "industry")
#let industry(data) = data.cv.experience.filter(e => e.at("kind", default: "research") == "industry")
