// Shared layout of the two PDF CVs (resume.typ: 1 page, full.typ: 2 pages).
// Content comes from dist/cv/data.json, generated by the website build from
// src/data/*.yaml: edit the YAML files, not this template.
//
// Layout: a narrow left column (dates, venues, skill groups) and the content on
// the right, so every section shares the same vertical rhythm.

#let ink = rgb("#1d1f24")
#let accent = rgb("#9e1b32")
#let soft = rgb("#5f6168")
#let faint = rgb("#8a8c93")
#let hair = rgb("#d9d6d0")

#let serif = "Source Serif 4"
#let sans = "Source Sans 3"

#let side = 2.35cm   // width of the left column
#let gap = 0.9em     // gutter between the two columns

// Tiny Markdown subset used in the YAML files: **bold**, *italic*.
#let md(s) = {
  let t = s
  for c in ("\\", "#", "$", "@", "<", ">", "_", "~", "`", "[", "]", "=", "-", "+", "/") {
    t = t.replace(c, "\\" + c)
  }
  t = t.replace(regex("\*\*(.+?)\*\*"), m => "BOLD{" + m.captures.at(0) + "}BOLD")
  t = t.replace(regex("\*(.+?)\*"), m => "\_" + m.captures.at(0) + "\_")
  t = t.replace("\\_", "_").replace("BOLD{", "*").replace("}BOLD", "*")
  eval(t, mode: "markup")
}

#let setup(body) = {
  set document(author: "Emilien Seiler")
  set page(paper: "a4", margin: (left: 1.7cm, right: 1.7cm, top: 1.5cm, bottom: 1.3cm))
  set text(font: sans, size: 9.8pt, fill: ink, lang: "en", number-type: "lining")
  set par(justify: false, leading: 0.56em, spacing: 0.62em)
  set list(indent: 0pt, body-indent: 0.55em, spacing: 0.38em, marker: text(fill: accent, size: 0.8em, baseline: -0.05em, "▸"))
  show link: set text(fill: ink)
  body
}

// Two-column row: `left` in the narrow column, `body` on the right.
#let row(left, body, below: 0.7em) = block(below: below, breakable: false, grid(
  columns: (side, 1fr),
  column-gutter: gap,
  align(right, left),
  body,
))

#let header(data, phone: none) = {
  let p = data.profile
  let l = p.links
  let contact = (
    link("mailto:" + l.email, l.email),
    link(data.site, data.site.replace("https://", "")),
    ..if l.at("github", default: "") != "" { (link(l.github, "github.com/" + l.github.split("/").last()),) },
    ..if l.at("scholar", default: "") != "" { (link(l.scholar, "Google Scholar"),) },
    ..if l.at("linkedin", default: "") != "" { (link(l.linkedin, "LinkedIn"),) },
    ..if phone != none and phone != "" { (phone,) },
  )
  grid(
    columns: (1fr, auto),
    align: (left + bottom, right + bottom),
    [
      #text(font: serif, size: 25pt, weight: 600, tracking: -0.01em, p.name)
      #v(-0.9em)
      #text(size: 10.5pt, fill: soft)[#p.role #h(0.3em)#text(fill: hair, "|")#h(0.3em) #p.affiliation]
    ],
    text(size: 8.8pt, fill: soft, contact.join(linebreak())),
  )
  v(0.2em)
  line(length: 100%, stroke: 1.4pt + accent)
  v(0.15em)
}

// Section title across the page, followed by a hairline.
#let section(title) = {
  v(0.55em)
  block(below: 0.65em, sticky: true, grid(  // sticky: never alone at the bottom of a page
    columns: (auto, 1fr),
    column-gutter: 0.6em,
    align: horizon,
    text(font: serif, size: 12pt, weight: 600, fill: accent, title),
    line(length: 100%, stroke: 0.6pt + hair),
  ))
}

#let when(s) = text(size: 8.8pt, fill: faint, str(s))

// One CV entry. `short: true` uses the one-line `short` text when present.
#let entry(e, short: false) = {
  let org = e.at("org", default: none)
  // City only ("Lausanne, Switzerland" -> "Lausanne"); the 1-page resume leaves it out.
  let place = if short { none } else { e.at("place", default: none) }
  if place != none { place = place.split(",").first() }
  let s = e.at("short", default: none)
  let details = e.at("details", default: ())
  row(when(e.period))[
    #set block(spacing: 0.38em)
    #grid(
      columns: (1fr, auto),
      column-gutter: 0.8em,
      [#text(weight: 700, e.title)#if org != none [#h(0.35em)#text(fill: soft, style: "italic", org)]],
      if place != none { text(size: 8.8pt, fill: faint, place) },
    )
    #set par(spacing: 0.24em)
    #if short and s != none {
      if s != "" { text(size: 9.2pt, fill: soft, md(s)) }
    } else if details.len() > 0 {
      set text(size: 9.2pt)
      list(..details.map(md))
    }
  ]
}

#let entries(list, short: false) = for e in list { entry(e, short: short) }

#let publication(p) = {
  let authors = p.authors.map(a => {
    let n = if a.equal { a.name + "*" } else { a.name }
    if a.me { text(weight: 700, fill: ink, n) } else { n }
  })
  // The year sits in the left column; the venue line is skipped when it is only the year.
  let venue = if p.venue != str(p.year) { p.venue }
  row(when(p.year), below: 0.72em)[
    #set par(spacing: 0.3em, leading: 0.45em)
    #link(p.url, text(weight: 600, p.title)) \
    #text(size: 9pt, fill: soft)[#authors.join(", ")]
    #if venue != none [\ #text(size: 9pt, style: "italic", weight: 600, fill: accent, venue)]
  ]
}

#let skills(list) = for s in list {
  row(text(size: 9pt, weight: 700, fill: soft, s.group), below: 0.5em, text(size: 9.2pt, s.items.join("  ·  ")))
}

// A single plain line aligned with the content column (e.g. a link or a note).
#let note(body) = row([], text(size: 8.8pt, fill: faint, body))

#let research(data) = data.cv.experience.filter(e => e.at("kind", default: "research") != "industry")
#let industry(data) = data.cv.experience.filter(e => e.at("kind", default: "research") == "industry")
