// Layout of the 1-page PDF CV (resume.typ).
// Content comes from dist/cv/data.json, generated by the website build from
// src/data/*.yaml: edit the YAML files, not this template.
//
// Layout: a narrow left column (dates, venues, skill groups) and the content on
// the right, so every section shares the same vertical rhythm.

#let ink = rgb("#1d1f24")
#let accent = rgb("#9e1b32")
#let soft = rgb("#5f6168")
#let faint = rgb("#8a8c93")
#let hair = rgb("#d9d6d0")

#let serif = "Source Serif 4"
#let sans = "Source Sans 3"

#let side = 2.35cm   // width of the left column
#let gap = 0.9em     // gutter between the two columns

// Tiny Markdown subset used in the YAML files: **bold**, *italic*, [links](https://...).
#let md-inline(s) = {
  let t = s
  for c in ("\\", "#", "$", "@", "<", ">", "_", "~", "`", "[", "]", "=", "-", "+", "/") {
    t = t.replace(c, "\\" + c)
  }
  t = t.replace(regex("\*\*(.+?)\*\*"), m => "BOLD{" + m.captures.at(0) + "}BOLD")
  t = t.replace(regex("\*(.+?)\*"), m => "\_" + m.captures.at(0) + "\_")
  t = t.replace("\\_", "_").replace("BOLD{", "*").replace("}BOLD", "*")
  eval(t, mode: "markup")
}

#let md(s) = {
  let out = []
  let pos = 0
  for m in s.matches(regex("\\[([^\\]]+)\\]\\(([^)\\s]+)\\)")) {
    out += md-inline(s.slice(pos, m.start))
    out += link(m.captures.at(1), text(fill: accent, md-inline(m.captures.at(0))))
    pos = m.end
  }
  out + md-inline(s.slice(pos))
}

#let setup(body) = {
  set document(author: "Emilien Seiler")
  set page(paper: "a4", margin: (left: 1.8cm, right: 1.8cm, top: 1.6cm, bottom: 1.4cm))
  set text(font: sans, size: 10pt, fill: ink, lang: "en", number-type: "lining")
  set par(justify: false, leading: 0.68em, spacing: 0.75em)
  set list(indent: 0pt, body-indent: 0.55em, spacing: 0.55em, marker: text(fill: accent, size: 0.8em, baseline: -0.05em, "▸"))
  show link: set text(fill: ink)
  body
}

// Two-column row: `left` in the narrow column, `body` on the right.
#let row(left, body, below: 1.05em) = block(below: below, breakable: false, grid(
  columns: (side, 1fr),
  column-gutter: gap,
  align(right, left),
  body,
))

// Round, clickable icon (like on the website). Icons: cv/icons/*.svg (Font Awesome Free).
#let icon-link(url, name) = link(url, box(
  width: 17pt, height: 17pt, radius: 50%, stroke: 0.6pt + hair, inset: 3.6pt,
  align(center + horizon, image("icons/" + name + ".svg", height: 100%)),
))

#let header(data, phone: none) = {
  let p = data.profile
  let l = p.links
  let icons = (
    ("website", data.site),
    ("github", l.at("github", default: "")),
    ("scholar", l.at("scholar", default: "")),
    ("linkedin", l.at("linkedin", default: "")),
    ("orcid", l.at("orcid", default: "")),
  ).filter(((_, url)) => url != "")
  grid(
    columns: (1fr, auto),
    align: (left + bottom, right + bottom),
    [
      #text(font: serif, size: 25pt, weight: 600, tracking: -0.01em, p.name)
      #v(-0.9em)
      #text(size: 10.5pt, fill: soft)[#p.role #h(0.3em)#text(fill: hair, "|")#h(0.3em) #p.affiliation]
    ],
    [
      #set text(size: 9pt, fill: soft)
      #link("mailto:" + l.email, l.email)
      #if phone != none and phone != "" [ \ #phone]
      #v(-0.25em)
      #icons.map(((name, url)) => icon-link(url, name)).join(h(0.3em))
    ],
  )
  v(0.45em)
  line(length: 100%, stroke: 1.4pt + accent)
  v(0.2em)
}

#let section(title) = {
  v(1.1em)
  block(below: 0.85em, sticky: true, grid(  // sticky: never alone at the bottom of a page
    columns: (auto, 1fr),
    column-gutter: 0.6em,
    align: horizon,
    text(font: serif, size: 12pt, weight: 600, fill: accent, title),
    line(length: 100%, stroke: 0.6pt + hair),
  ))
}

#let when(s) = text(size: 8.8pt, fill: faint, str(s))

// One CV entry. `short: true` uses the one-line `short` text when present.
#let entry(e, short: false) = {
  let org = e.at("org", default: none)
  // City only ("Lausanne, Switzerland" -> "Lausanne"); the 1-page resume leaves it out.
  let place = if short { none } else { e.at("place", default: none) }
  if place != none { place = place.split(",").first() }
  let s = e.at("short", default: none)
  let details = e.at("details", default: ())
  row(when(e.period))[
    #set block(spacing: 0.55em)
    #grid(
      columns: (1fr, auto),
      column-gutter: 0.8em,
      [#text(weight: 700, e.title)#if org != none [#h(0.35em)#text(fill: soft, style: "italic", org)]],
      if place != none { text(size: 8.8pt, fill: faint, place) },
    )
    #set par(spacing: 0.24em)
    #if short and s != none {
      if s != "" { text(size: 9.2pt, fill: soft, md(s)) }
    } else if details.len() > 0 {
      set text(size: 9.2pt)
      list(..details.map(md))
    }
  ]
}

#let entries(list, short: false) = for e in list { entry(e, short: short) }

// `max`: shorten long author lists to the first authors + me + "et al."
#let publication(p, max: none) = {
  let list = p.authors
  if max != none and list.len() > max {
    let mine = list.position(a => a.me)
    list = if mine == none or mine < max { list.slice(0, max) } else { list.slice(0, max - 1) + (list.at(mine),) }
    list.push((name: "et al.", me: false, equal: false))
  }
  let authors = list.map(a => {
    let n = if a.equal { a.name + "*" } else { a.name }
    if a.me { text(weight: 700, fill: ink, n) } else { n }
  })
  // The year sits in the left column; the venue line is skipped when it is only the year.
  let venue = if p.venue != str(p.year) { p.venue }
  row(when(p.year), below: 0.95em)[
    #set par(spacing: 0.4em, leading: 0.55em)
    #link(p.url, text(weight: 600, p.title)) \
    #text(size: 9pt, fill: soft)[#authors.join(", ")]
    #if venue != none [\ #text(size: 9pt, style: "italic", weight: 600, fill: accent, venue)]
  ]
}

#let skills(list) = for s in list {
  row(text(size: 9pt, weight: 700, fill: soft, s.group), below: 0.6em, text(size: 9.2pt, s.items.join("  ·  ")))
}

// A single plain line aligned with the content column (e.g. a link or a note).
#let note(body) = row([], text(size: 8.8pt, fill: faint, body))

// Newest first by start year; ongoing ("present") entries first within a year.
#let newest-first(list) = list.sorted(key: e => {
  let p = str(e.period)
  let y = p.find(regex("\d{4}"))
  (if y == none { 0 } else { int(y) }, if p.contains("present") { 1 } else { 0 })
}).rev()

// Summary paragraph under the header (cv.yaml: summary).
#let summary(data) = {
  let s = data.cv.at("summary", default: none)
  if s != none and s != "" {
    block(above: 0.9em, below: 0.2em, text(size: 9.8pt, fill: soft, md(s)))
  }
}
